# Generated by Django 5.1.5 on 2025-02-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('forecast_date', models.DateField()),
                ('values', models.JSONField(default=list)),
            ],
        ),
    ]
