# Generated by Django 5.1.5 on 2025-02-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Forecast',
        ),
    ]
